export interface TradeGoodModel {
    TradeGoodsId: number,
    TradeGoodsCode: string,
    TradeGoodsName: string,
    IsForceInputSerialNumber: boolean,
    IsForceInputOneVATOnPaper: boolean,
    Note: string,
    InValid: boolean,
    Disable: boolean,
    TimeStamp: string[],
    TimeStampCode: string[],
    ClientCode: string,
    SyncCode: string,
    IsGame: boolean,
    IMDB_Report_OrderNumber: number,
    Allow_BanHang_GiaNhoHonOrBangZero: boolean,
    AutoLogOnCode_LastUpdate_ById: number,
    AutoLogOnCode_LastUpdate_ByFullName: string,
    AutoLogOnCode_LastUpdate_DateTime: string,
    AutoLogOnCode_LastUpdate_IP: string,
    AutoLogOnCode_LastUpdate_ComputerName: string,
    AutoLogOnCode_LastUpdate_MACAddress: string,
    IsDeleted: boolean,
    IsCinema: boolean,
    DontUseInPaymentReport_WhenRequest: boolean,
    BarcodeSupport: string,
    TradeGoodsCode_For_Export: string,
    Is_TradeGoodsCode_For_Export_Default: boolean,
    IsNeedMarkDefault4Material: boolean,
    IsRestaurant: boolean,
    TimeStampText: string,
    IsDisplayOnWeb: boolean,
    TradeGoodsName_English: string,
    IsSystem: boolean,
    IsWithUnit: boolean

}